### ISSUE TITLE
Pas de son sur Firefox

### ISSUE THREAD

**Issue by DENOISV** [bendenois/game#3]
Pas de son sur le MP3 sur Firefox, OK sur MP4 bien qu'un peu long à démarrer

**Comment by DENOISV** [comment]
Marche parfois, peut être pas un bug du code mais accès au fichiers de musique

**Comment by bendenois** [comment]
Peut etre des erreurs sur le chemin de certains fichiers, il y en avait certains avec des apostrophes, j'ai mis \' mais du coup j'ai des doutes sur le fait que ça marche. 
Note les videos qui marchent pas.
